%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/lea.schuh/Documents/PhD/ICB/Xenopus/HistonesXenopus/data/DTdata.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/11/18 18:49:00

%% Import the data
[~, ~, raw] = xlsread('../HistonesXenopus/data/DTdata.xlsx','Sheet1');
raw = raw(53:end,1:2);

%% Create output variable
DTdata = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;