%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\lea.schuh\Documents\Praktikum\H4K20states.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/04 14:17:51

%% Import the data
[~, ~, raw] = xlsread('../HistonesXenopus/data/H4K20states_dummy.xlsx','Sheet1','C4:J15');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
H4K20states = table;

%% Allocate imported array to column variable names
H4K20states.M13mock = data(:,1)/100;
H4K20states.M18mock = data(:,2)/100;
H4K20states.M25mock = data(:,3)/100;
H4K20states.M32mock = data(:,4)/100;
H4K20states.M13HUA = data(:,5)/100;
H4K20states.M18HUA = data(:,6)/100;
H4K20states.M25HUA = data(:,7)/100;
H4K20states.M32HUA = data(:,8)/100;

%% Clear temporary variables
clearvars data raw;

%% Create data structures DA and DB

DA(1).t = [9.25 14.25 22 34.5];
DA(1).y = log(transpose([H4K20states.M13mock(1:4), H4K20states.M18mock(1:4), H4K20states.M25mock(1:4), H4K20states.M32mock(1:4)]));
DA(2).t = [9.25 14.25 22 34.5];
DA(2).y = log(transpose([H4K20states.M13mock(5:8), H4K20states.M18mock(5:8), H4K20states.M25mock(5:8), H4K20states.M32mock(5:8)]));
DA(3).t = [9.25 14.25 22 34.5];
DA(3).y = log(transpose([H4K20states.M13mock(9:12), H4K20states.M18mock(9:12), H4K20states.M25mock(9:12), H4K20states.M32mock(9:12)]));

DB(1).t = [9.25 14.25 22 34.5];
DB(1).y = log(transpose([H4K20states.M13HUA(1:4), H4K20states.M18HUA(1:4), H4K20states.M25HUA(1:4), H4K20states.M32HUA(1:4)]));
DB(2).t = [9.25 14.25 22 34.5];
DB(2).y = log(transpose([H4K20states.M13HUA(5:8), H4K20states.M18HUA(5:8), H4K20states.M25HUA(5:8), H4K20states.M32HUA(5:8)]));
DB(3).t = [9.25 14.25 22 34.5];
DB(3).y = log(transpose([H4K20states.M13HUA(9:12), H4K20states.M18HUA(9:12), H4K20states.M25HUA(9:12), H4K20states.M32HUA(9:12)]));