%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/lea.schuh/Documents/GitHub/HistonesXenopus/data/H4K20MO.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/07/20 14:40:52

%% Import the data
[~, ~, raw] = xlsread('/Users/lea.schuh/Documents/GitHub/HistonesXenopus/data/H4K20MO.xlsx','Sheet1');
raw = raw(2:5,2:end);

%% Create output variable
H4K20MO = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;